---
- hosts: 3.134.101.193
  become: yes
  tasks:
  - name: install mariadb server
    yum:
      name=mariadb-server
      state=latest
    tags:
    - install
  - name: start maria db
    service:
      name=mariadb
      state=started
    tags:
    - start
